import 'package:flutter_screenutil/flutter_screenutil.dart';

class SizeConfig {
  // Screen dimensions
  static double getScreenWidth() => ScreenUtil().screenWidth;
  static double getScreenHeight() => ScreenUtil().screenHeight;

  // Font sizes
  static final double fontSize_2 = 2.sp;
  static final double fontSize_4 = 4.sp;
  static final double fontSize_6 = 6.sp;
  static final double fontSize_8 = 8.sp;
  static final double fontSize_10 = 10.sp;
  static final double fontSize_12 = 12.sp;
  static final double fontSize_14 = 14.sp;
  static final double fontSize_16 = 16.sp;
  static final double fontSize_18 = 18.sp;
  static final double fontSize_20 = 20.sp;
  static final double fontSize_22 = 22.sp;
  static final double fontSize_24 = 24.sp;
  static final double fontSize_26 = 26.sp;
  static final double fontSize_28 = 28.sp;
  static final double fontSize_30 = 30.sp;
  static final double fontSize_32 = 32.sp;
  static final double fontSize_34 = 34.sp;
  static final double fontSize_36 = 36.sp;
  static final double fontSize_38 = 38.sp;
  static final double fontSize_40 = 40.sp;
  static final double fontSize_42 = 42.sp;
  static final double fontSize_44 = 44.sp;
  static final double fontSize_46 = 46.sp;
  static final double fontSize_48 = 48.sp;
  static final double fontSize_50 = 50.sp;

  // Heights and Widths
  static final double height_2 = 2.h;
  static final double height_4 = 4.h;
  static final double height_6 = 6.h;
  static final double height_8 = 8.h;
  static final double height_10 = 10.h;
  static final double height_12 = 12.h;
  static final double height_14 = 14.h;
  static final double height_16 = 16.h;
  static final double height_18 = 18.h;
  static final double height_20 = 20.h;
  static final double height_22 = 22.h;
  static final double height_24 = 24.h;
  static final double height_26 = 26.h;
  static final double height_28 = 28.h;
  static final double height_30 = 30.h;
  static final double height_32 = 32.h;
  static final double height_34 = 34.h;
  static final double height_36 = 36.h;
  static final double height_38 = 38.h;
  static final double height_40 = 40.h;
  static final double height_42 = 42.h;
  static final double height_44 = 44.h;
  static final double height_46 = 46.h;
  static final double height_48 = 48.h;
  static final double height_50 = 50.h;
  static final double height_64 = 64.h;

  static final double width_2 = 2.w;
  static final double width_3 = 3.w;
  static final double width_4 = 4.w;
  static final double width_6 = 6.w;
  static final double width_8 = 8.w;
  static final double width_10 = 10.w;
  static final double width_12 = 12.w;
  static final double width_14 = 14.w;
  static final double width_16 = 16.w;
  static final double width_18 = 18.w;
  static final double width_20 = 20.w;
  static final double width_22 = 22.w;
  static final double width_24 = 24.w;
  static final double width_26 = 26.w;
  static final double width_28 = 28.w;
  static final double width_30 = 30.w;
  static final double width_32 = 32.w;
  static final double width_34 = 34.w;
  static final double width_35 = 35.w;
  static final double width_36 = 36.w;
  static final double width_38 = 38.w;
  static final double width_40 = 40.w;
  static final double width_42 = 42.w;
  static final double width_44 = 44.w;
  static final double width_46 = 46.w;
  static final double width_48 = 48.w;
  static final double width_50 = 50.w;
  static final double width_54 = 54.w;
  static final double width_60 = 60.w;
  static final double width_70 = 70.w;
  static final double width_100 = 100.w;
  static final double width_115 = 115.w;
  static final double width_120 = 120.w;
  static final double width_140 = 140.w;
  static final double width_150 = 150.w;

  // Radius
  static final double radius_2 = 2.r;
  static final double radius_4 = 4.r;
  static final double radius_6 = 6.r;
  static final double radius_8 = 8.r;
  static final double radius_10 = 10.r;
  static final double radius_12 = 12.r;
  static final double radius_14 = 14.r;
  static final double radius_16 = 16.r;
  static final double radius_18 = 18.r;
  static final double radius_20 = 20.r;
  static final double radius_22 = 22.r;
  static final double radius_24 = 24.r;
  static final double radius_26 = 26.r;
  static final double radius_28 = 28.r;
  static final double radius_30 = 30.r;
  static final double radius_32 = 32.r;
  static final double radius_34 = 34.r;
  static final double radius_36 = 36.r;
  static final double radius_38 = 38.r;
  static final double radius_40 = 40.r;
  static final double radius_42 = 42.r;
  static final double radius_44 = 44.r;
  static final double radius_46 = 46.r;
  static final double radius_48 = 48.r;
  static final double radius_50 = 50.r;
}
